### ISSUE TITLE
请求引用

### ISSUE THREAD

**Issue by drinktoomuchsax** [CCcmill/EE313-2023Fall#1]
学姐/学长/同学/好大儿好，请求在[SUSTech-EE-Course-Hero](https://github.com/drinktoomuchsax/SUSTech-EE-Course-Hero)里引用你的项目以及引用你的仓库内容：)

**Comment by CCcmill** [comment]
好大儿拿去用吧：）

**Comment by drinktoomuchsax** [comment]
感谢
